#!/bin/sh -x

set -e

test -e wvstreams/Makefile || ./get-git-modules

rm -f config.mk
cat >config.mk <<-EOF
	CONFIGHOST=--host=i586-mingw32msvc
	CC=i586-mingw32msvc-gcc
	AR=i586-mingw32msvc-ar
	ARRC=\$(AR) rc
	RANLIB=i586-mingw32msvc-ranlib
	WV_BUILD_MINGW=1
	export CC AR RANLIB
EOF

make wvports/zlib wvports/openssl wvports/dbus wvports/boost wvports/win32api

echo "--> Configuring WvStreams..."
(cd wvstreams && ./autogen.sh)
(set -x; cd wvstreams && \
	XCPPFLAGS="-I../wvports/boost/build/boost" \
	./configure-mingw32 \
		--disable-debug \
		--disable-optimization \
		--with-openssl=../wvports/openssl/build/openssl \
		--with-zlib=../wvports/zlib/build/zlib \
		--with-dbus=../wvports/dbus/build/dbus \
		"$@") || exit $?

