
include ../wvports.mk

# Really no reason that we need to get the sources of w32api and compile them
# since we're not shipping these out to Windows users; they have their own set.

define unpack
	ln -s . $(BUILDDIR)/w32api
endef

define prepare
endef

define compile
endef
